'use strict';
(() => {
  const el=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const NA='DATO NO DISPONIBLE', levels={PDH:'Previo Día Alto',PDL:'Previo Día Bajo',PMH:'Premercado Alto',PML:'Premercado Bajo',ORH:'Apertura Rango Alto',ORL:'Apertura Rango Bajo'};
  const number=v=>typeof v==='number'&&Number.isFinite(v)?new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:4}).format(v):NA;
  const clock=(t,tz,date=false)=>{if(!t||!tz)return NA;try{return new Intl.DateTimeFormat('es-PE',{timeZone:tz,hour:'2-digit',minute:'2-digit',...(date?{day:'2-digit',month:'2-digit',year:'numeric'}:{})}).format(new Date(t));}catch{return NA;}};
  let endpoint=localStorage.getItem('br_endpoint')||(['localhost','127.0.0.1'].includes(location.hostname)?location.origin:''),token='',connected=false,busy=new Set();
  const profiles=new Map(),frames=new Map(),indicators=new Map(),historyCache=new Map();
  const fallback=i=>({id:i,configured:i===1,meta:i===1?{ticker:'CSPX',name:'iShares Core S&P 500',exchange:'LSEETF',currency:'USD',timezone:'Europe/London',market:'LONDON'}:null,config:{tolerance:0},message:i===1?'Conexión IBKR pendiente':'Activo configurable'});
  for(let i=1;i<=4;i++)profiles.set(i,fallback(i));
  async function api(path,options={}){
    if(!endpoint||!token)throw Error('Conecta el servicio IBKR para consultar datos reales.');
    const r=await fetch(endpoint+path,{...options,headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json'},signal:AbortSignal.timeout(15000),cache:'no-store',credentials:'omit'});
    if(!r.ok){let detail='No se pudo consultar el servicio ('+r.status+').';try{const d=await r.json();detail=typeof d.detail==='string'?d.detail:detail;}catch{}throw Error(detail);}return r.json();
  }
  function connection(ok,message){connected=ok;el('brConnection').textContent=ok?'Servicio de análisis conectado':'Conexión IBKR pendiente';el('brConnectionDetail').textContent=message;el('brConnectButton').textContent=ok?'Conexión':'Conectar IBKR';document.querySelector('.br-dot').style.background=ok?'var(--good)':'var(--warn)';}
  function chart(p,minutes,showIndicators){
    const bars=(minutes===15?p.bars15:p.bars)||[];
    if(!bars.length)return '<div class="br-chart-empty"><strong>'+NA+'</strong><p>'+(p.configured?'Aquí aparecerán las velas reales de IBKR y los cuatro niveles de este activo.':'Configura este perfil para identificar su mercado y cargar las velas.')+'</p></div>';
    const view=bars.slice(-70),validLevels=(p.levels||[]).filter(l=>typeof l.price==='number'&&new Date(l.available_at)<=new Date(view.at(-1).time));
    const prices=view.flatMap(b=>[b.high,b.low]).concat(validLevels.map(l=>l.price));let lo=Math.min(...prices),hi=Math.max(...prices),pad=(hi-lo)*.12||1;lo-=pad;hi+=pad;
    const W=680,H=280,left=12,right=82,top=15,bottom=35,plotW=W-left-right,plotH=H-top-bottom;
    const y=v=>top+(hi-v)/(hi-lo)*plotH,step=plotW/view.length,x=i=>left+(i+.5)*step;
    let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Velas de ${minutes} minutos de ${esc(p.meta.ticker)} con niveles y zonas"><title>${esc(p.meta.ticker)} · IBKR · ${minutes} minutos</title>`;
    for(let j=0;j<5;j++){const v=lo+(hi-lo)*j/4;svg+=`<line x1="${left}" x2="${W-right}" y1="${y(v)}" y2="${y(v)}" stroke="var(--border)" opacity=".5"/><text x="${W-right+5}" y="${y(v)+4}" fill="currentColor" font-size="10">${esc(number(v))}</text>`;}
    for(const l of validLevels){const tol=p.config?.tolerance||0,yy=y(l.price),height=Math.max(3,y(l.price-tol)-y(l.price+tol));svg+=`<rect x="${left}" y="${yy-height/2}" width="${plotW}" height="${height}" fill="var(--accent)" opacity=".12"/><line x1="${left}" x2="${W-right}" y1="${yy}" y2="${yy}" stroke="var(--accent)" stroke-dasharray="5 4"><title>${esc(l.label)} · ${esc(number(l.price))}</title></line>`;}
    view.forEach((b,i)=>{const color=b.close>=b.open?'var(--good)':'var(--bad)',xx=x(i),w=Math.max(2,step*.6);svg+=`<g><title>${esc(clock(b.time,p.meta.timezone,true))} hora de la bolsa · ${esc(clock(b.time,'America/Lima',true))} hora Perú | OPEN · Apertura ${number(b.open)} | HIGH · Máximo ${number(b.high)} | LOW · Mínimo ${number(b.low)} | CLOSE · Cierre ${number(b.close)} | VOLUME · Volumen ${number(b.volume)}</title><line x1="${xx}" x2="${xx}" y1="${y(b.high)}" y2="${y(b.low)}" stroke="${color}"/><rect x="${xx-w/2}" y="${Math.min(y(b.open),y(b.close))}" width="${w}" height="${Math.max(1,Math.abs(y(b.open)-y(b.close)))}" fill="${color}"/></g>`;});
    if(showIndicators){
      for(const [n,color] of [[9,'#ffc66d'],[21,'#b7a0ff']]){let avg=null,pts=[];bars.forEach((b,i)=>{if(i===n-1)avg=bars.slice(0,n).reduce((s,c)=>s+c.close,0)/n;else if(i>=n)avg=b.close*2/(n+1)+avg*(1-2/(n+1));if(avg!==null&&i>=bars.length-view.length)pts.push(`${x(i-(bars.length-view.length))},${y(avg)}`);});if(pts.length)svg+=`<polyline points="${pts.join(' ')}" fill="none" stroke="${color}" stroke-width="1.3"><title>EMA ${n} · Media móvil exponencial</title></polyline>`;}
      let sum=0,vol=0,ok=true,pts=[];bars.forEach((b,i)=>{if(b.volume===null||b.volume<0||(b.volume>0&&!(b.wap>0)))ok=false;if(ok){sum+=b.wap*b.volume;vol+=b.volume;if(vol&&i>=bars.length-view.length)pts.push(`${x(i-(bars.length-view.length))},${y(sum/vol)}`);}});if(pts.length)svg+=`<polyline points="${pts.join(' ')}" fill="none" stroke="var(--text)" stroke-width="1.2"><title>VWAP · Precio medio ponderado por volumen</title></polyline>`;
    }
    const entry=p.selected?.entry;if(typeof entry==='number')svg+=`<line x1="${left}" x2="${W-right}" y1="${y(entry)}" y2="${y(entry)}" stroke="var(--good)" stroke-dasharray="2 5"><title>Entrada de referencia ${esc(number(entry))}</title></line>`;
    for(const i of [0,Math.floor(view.length/2),view.length-1])svg+=`<text x="${x(i)}" y="${H-12}" fill="currentColor" text-anchor="${i===0?'start':i===view.length-1?'end':'middle'}" font-size="10">${esc(clock(view[i].time,p.meta.timezone))}</text>`;
    return svg+'</svg>';
  }
  function card(i){
    const p=profiles.get(i),m=p.meta||(p.config?.conid===76023663&&p.config?.exchange==='LSEETF'?fallback(1).meta:{}),c=p.confirmations||{},minutes=frames.get(i)||2,show=indicators.get(i)||false;
    const codes=p.levels?.map(l=>l.code)||(m.market==='LONDON'?['PDH','PDL','ORH','ORL']:m.market==='US'?['PDH','PDL','PMH','PML']:[]);
    const live=connected&&!p.error,age=p.updated_at?(Date.now()-new Date(p.updated_at).getTime())/1000:Infinity,barAge=p.last_bar?(Date.now()-new Date(p.last_bar).getTime())/1000:Infinity,active=live&&p.quality==='Actual'&&age>=0&&age<180&&barAge>=0&&barAge<180,setup=active?(p.state_label||'⚪ ESPERANDO'):'⚪ ESPERANDO';
    const title=m.ticker||'Seleccionar activo',entryValid=active&&p.entry_available;
    const levelHTML=codes.length?codes.map(code=>{const l=p.levels?.find(x=>x.code===code),v=l?.price;return `<div class="br-level"><b>${code}</b><span>${levels[code]}</span><strong class="${typeof v==='number'?'':'empty'}">${number(v)}</strong></div>`;}).join(''):'<div class="br-empty-levels">Los niveles se identificarán según el mercado.</div>';
    const datum=(title,value,sub='')=>`<div><span>${title}</span><b>${esc(value??NA)}</b>${sub?`<span>${esc(sub)}</span>`:''}</div>`;
    return `<article class="br-profile" id="brProfile${i}"><div class="br-profile-head"><div><div class="br-caption">PERFIL ${i}</div><h2>${esc(title)}</h2><small>${esc(m.name||'Independiente de los demás perfiles')}</small></div><div class="br-profile-actions"><button class="btn" data-action="configure" data-id="${i}">Configurar</button><button class="btn" data-action="refresh" data-id="${i}" ${busy.has(i)?'disabled':''}><svg class="br-refresh-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 7v5h-5M4 17v-5h5M6 7a7 7 0 0 1 12-1l2 2M4 16l2 2a7 7 0 0 0 12-1"/></svg> Actualizar</button></div></div><div class="br-body">
      <div class="br-meta"><span>${esc(m.exchange||'Bolsa por identificar')} · ${esc(m.currency||'Moneda por identificar')}</span><span>${esc(m.timezone||'Zona horaria por identificar')}</span></div>
      <div class="br-status" data-state="${active?esc(p.state||'waiting'):'waiting'}"><strong>${esc(setup)}</strong><small>${esc(p.error||p.message||'Esperando datos')} · ${esc(p.quality||'Sin datos de mercado')}</small></div>
      <div class="br-meta"><div><div class="br-price-label">Precio actual · ${esc(m.currency||'moneda pendiente')}</div><div class="br-price ${active&&typeof p.price==='number'?'':'empty'}">${active?number(p.price):NA}</div></div><div class="br-clock" data-clock="${i}">Hora de la bolsa: ${clock(new Date(),m.timezone)}<br>Hora Perú: ${clock(new Date(),'America/Lima')}</div></div>
      <div class="br-levels">${levelHTML}</div>
      <div class="br-chartbar"><label>Velas <select data-frame="${i}" aria-label="Marco del perfil ${i}"><option value="2" ${minutes===2?'selected':''}>2 minutos</option><option value="15" ${minutes===15?'selected':''}>15 minutos</option></select></label><label><input type="checkbox" data-indicators="${i}" ${show?'checked':''}> Mostrar indicadores</label><span>${p.bars?.length?'Fuente: IBKR':'Esperando IBKR'}</span></div>
      <div class="br-chart">${chart(p,minutes,show)}</div><div class="br-legend">${codes.map(code=>`<span>${code} · ${levels[code]}</span>`).join('')}</div>${show?'<div class="br-legend">EMA 9 · Media exponencial de 9 períodos · EMA 21 · Media exponencial de 21 períodos · VWAP · Precio medio ponderado por volumen</div>':''}
      <div class="br-annotation">${p.last_bar?'Última vela cerrada: '+esc(clock(p.last_bar,m.timezone,true))+' bolsa · '+esc(clock(p.last_bar,'America/Lima',true))+' Perú':'Solo se analizarán velas cerradas.'}${p.session_open?'<br>Sesión oficial: '+clock(p.session_open,m.timezone)+'–'+clock(p.session_close,m.timezone)+' bolsa · '+clock(p.session_open,'America/Lima')+'–'+clock(p.session_close,'America/Lima')+' Perú':''}</div>
      <div class="br-entry"><strong class="${entryValid?'good':''}">${entryValid?'POSIBLE ENTRADA':'NO HAY ENTRADA CONFIRMADA'}</strong>${p.entry!==null&&p.entry!==undefined?`<p>Entrada de referencia: ${number(p.entry)} · ${esc(p.selected?.level?.label||'')}<br>Hora de la bolsa: ${clock(p.selected?.entry_time,m.timezone)} · Hora Perú: ${clock(p.selected?.entry_time,'America/Lima')}<br>Extremo posterior: ${number(p.selected?.extreme)} · Movimiento favorable: ${number(p.movement)} (${number(p.movement_percent)} %)<br>Hora del extremo: ${clock(p.selected?.extreme_time,m.timezone)} bolsa · ${clock(p.selected?.extreme_time,'America/Lima')} Perú</p>`:'<p>Esperar rompimiento, regreso y defensa del nivel.</p>'}</div>
      <div class="br-confirmations">${datum('EMA 9 / EMA 21 · Medias exponenciales',c.ema||'Sin determinar',number(c.ema9)+' / '+number(c.ema21))}${datum('VWAP · Precio medio por volumen',c.vwap_state||'Sin determinar',number(c.vwap))}${datum('VOLUME · Volumen',c.volume||NA)}${datum('CONFIRMACIÓN 15 MIN',c.fifteen===true?'Sí':c.fifteen===false?'No':NA)}${datum('BIAS · Sesgo del día',c.bias||'Sin determinar',typeof c.gap_percent==='number'?'Gap · Brecha de apertura: '+number(c.gap_percent)+' %':'Noticias: '+NA)}${datum('CONFIRMACIÓN CRUZADA',c.cross||NA,p.reference_meta?.ticker||'Referencia sin configurar')}</div>
      ${p.selected?.retest?`<details><summary>Vela del RETEST · Retesteo${p.selected.retest.volume==='Superior'?' · RETEST CON VOLUMEN ALTO · Retesteo con volumen alto':''}</summary><p>Nivel defendido: Sí · Mecha de rechazo: ${p.selected.retest.rejection?'Sí':'No'} · Martillo: ${p.selected.retest.hammer?'Sí':'No'}<br>Cuerpo: ${number(p.selected.retest.body)} · Mecha superior: ${number(p.selected.retest.upper_wick)} · Mecha inferior: ${number(p.selected.retest.lower_wick)}<br>Dirección: ${esc(p.selected.retest.direction)} · Volumen: ${esc(p.selected.retest.volume)}</p></details>`:''}
      <details data-history="${i}"><summary>Historial de este perfil</summary><div class="br-history" id="brHistory${i}">${historyCache.get(i)||'<p>Conecta IBKR para consultar el historial guardado.</p>'}</div><button class="btn" data-action="history" data-id="${i}">Consultar historial</button><button class="btn" data-action="export" data-id="${i}">Exportar historial</button></details>
      <div class="br-annotation">Última actualización: ${p.updated_at?clock(p.updated_at,'America/Lima',true)+' Perú':NA}</div>
    </div></article>`;
  }
  function render(i){
    if(i){const old=el('brProfile'+i),open=old?.querySelector('[data-history]')?.open;old.outerHTML=card(i);if(open)el('brProfile'+i).querySelector('[data-history]').open=true;}
    else el('brProfiles').innerHTML=[1,2,3,4].map(card).join('');
  }
  function markOffline(message){connection(false,message);for(const [i,p]of profiles){p.entry_available=false;render(i);}}
  async function refresh(i,manual=false){
    if(busy.has(i))return;
    if(!endpoint||!token){if(manual)connectDialog();return;}
    busy.add(i);render(i);
    try{const p=await api('/api/profiles/'+i);profiles.set(i,p);connection(true,'Lectura del servicio. El motor analiza automáticamente en segundo plano.');}
    catch(e){profiles.get(i).error=e.message;profiles.get(i).entry_available=false;}
    finally{busy.delete(i);render(i);}
  }
  async function refreshAll(manual=false){
    if(!endpoint||!token){if(manual)connectDialog();return;}
    try{const [data,status]=await Promise.all([api('/api/profiles'),api('/api/status')]);for(const p of data)profiles.set(p.id,p);connection(true,status.connected?'Motor independiente activo · consulta visual cada 15 segundos.':'Servicio conectado; TWS / IB Gateway todavía no está conectado.');render();}
    catch(e){markOffline(e.message);}
  }
  function dialog(content){const d=document.createElement('dialog');d.className='br-modal';d.innerHTML=content;document.body.append(d);d.querySelector('[data-close]')?.addEventListener('click',()=>d.close());d.addEventListener('close',()=>d.remove());d.showModal();return d;}
  function connectDialog(){
    const d=dialog(`<h2>Conectar el servicio IBKR</h2><p>El análisis necesita TWS o IB Gateway y el servicio privado en funcionamiento. GitHub Pages muestra sus resultados.</p><label for="brEndpoint">Dirección HTTPS del servicio</label><input id="brEndpoint" type="url" placeholder="https://tu-servicio.example" value="${esc(endpoint)}"><label for="brToken">Clave de acceso del servicio</label><input id="brToken" type="password" autocomplete="off" placeholder="No es tu contraseña de IBKR"><p>La clave permanece solo en esta pestaña. Nunca se publica ni se guarda en GitHub.</p><p><a href="https://github.com/smartsoftdevelop-alt/Precio-acciones---Dashboard/blob/main/backend/README.md" target="_blank" rel="noopener">Ver instrucciones de activación</a></p><div class="br-feedback" role="status"></div><div class="br-dialog-actions"><button class="btn" data-close>Cerrar</button><button class="btn primary" data-connect>Conectar</button></div>`);
    d.querySelector('[data-connect]').onclick=async()=>{
      const feedback=d.querySelector('.br-feedback'),button=d.querySelector('[data-connect]');
      try{const url=new URL(d.querySelector('#brEndpoint').value);if(url.protocol!=='https:'&&!(location.hostname==='localhost'||location.hostname==='127.0.0.1'))throw Error('La web publicada requiere una dirección HTTPS.');if(url.username||url.password||url.search||url.hash)throw Error('Usa la dirección base sin claves ni parámetros.');const candidate=url.origin+url.pathname.replace(/\/$/,'');const candidateToken=d.querySelector('#brToken').value;if(candidateToken.length<24)throw Error('La clave del servicio debe tener al menos 24 caracteres.');button.disabled=true;feedback.textContent='Comprobando conexión…';endpoint=candidate;token=candidateToken;await api('/api/status');localStorage.setItem('br_endpoint',endpoint);await refreshAll();d.close();}catch(e){feedback.textContent=e.message;button.disabled=false;}
    };
  }
  function configure(i){
    if(!connected){connectDialog();return;}
    const p=profiles.get(i),d=dialog(`<h2>Configurar perfil ${i}</h2><p>Busca el instrumento y comprueba la bolsa y moneda antes de guardar. No se sustituirá por otra variante.</p><label for="brSearch">Ticker o nombre</label><div class="br-searchline"><input id="brSearch" value="${esc(p.meta?.ticker||'')}"><button class="btn" data-search>Buscar</button></div><label for="brContract">Contrato IBKR</label><select id="brContract"><option value="">Selecciona un resultado</option></select><label for="brTolerance">Tolerancia del contacto, en unidades de precio</label><input id="brTolerance" type="number" min="0" max="100" step="any" value="${p.config?.tolerance||0}"><p>Ejemplo: 0,05 equivale a cinco centavos en USD. No modifica el cierre exigido para romper o invalidar.</p><label for="brRefSearch">Referencia opcional: ticker o índice</label><div class="br-searchline"><input id="brRefSearch" placeholder="SPX, SPY, QQQ…"><button class="btn" data-refsearch>Buscar</button></div><label for="brReference">Confirmación cruzada</label><select id="brReference"><option value="">Sin referencia</option></select><div class="br-feedback" role="status"></div><div class="br-dialog-actions"><button class="btn" data-close>Cancelar</button><button class="btn primary" data-save>Guardar perfil</button></div>`);
    let contracts=[],refs=[],existing=p.config?.conid?p.config:null,existingRef=p.config?.reference||null;
    if(existing){contracts=[{...existing,ticker:p.meta?.ticker||String(existing.conid),currency:p.meta?.currency||'',name:p.meta?.name||''}];}
    if(existingRef)refs=[{...existingRef,ticker:p.reference_meta?.ticker||String(existingRef.conid),currency:p.reference_meta?.currency||''}];
    function options(id,items,blank){d.querySelector(id).innerHTML=(blank?'<option value="">Sin referencia</option>':'<option value="">Selecciona un resultado</option>')+items.map((c,j)=>`<option value="${j}">${esc(c.ticker)} · ${esc(c.exchange)} · ${esc(c.currency)} · ${esc(c.name||'')} · ${c.conid}</option>`).join('');}
    options('#brContract',contracts,false);if(existing)d.querySelector('#brContract').value='0';options('#brReference',refs,true);if(existingRef)d.querySelector('#brReference').value='0';
    async function search(reference){const fb=d.querySelector('.br-feedback');fb.textContent='Buscando en IBKR…';try{const result=await api('/api/search?q='+encodeURIComponent(d.querySelector(reference?'#brRefSearch':'#brSearch').value));if(reference){refs=result;options('#brReference',refs,true);}else{contracts=result;options('#brContract',contracts,false);}fb.textContent=result.length?'Comprueba bolsa, moneda y contrato.':'No se encontraron instrumentos.';}catch(e){fb.textContent=e.message;}}
    d.querySelector('[data-search]').onclick=()=>search(false);d.querySelector('[data-refsearch]').onclick=()=>search(true);
    d.querySelector('[data-save]').onclick=async()=>{const fb=d.querySelector('.br-feedback'),btn=d.querySelector('[data-save]');try{const idx=d.querySelector('#brContract').value;if(idx==='')throw Error('Selecciona un contrato.');const c=contracts[Number(idx)],ri=d.querySelector('#brReference').value,r=ri===''?null:refs[Number(ri)],t=Number(d.querySelector('#brTolerance').value);if(!Number.isFinite(t)||t<0||t>100)throw Error('Tolerancia inválida.');btn.disabled=true;await api('/api/profiles/'+i,{method:'PUT',body:JSON.stringify({conid:c.conid,exchange:c.exchange,tolerance:t,reference:r?{conid:r.conid,exchange:r.exchange}:null})});historyCache.delete(i);await refresh(i);d.close();}catch(e){fb.textContent=e.message;btn.disabled=false;}};
  }
  async function history(i,exportFile=false){
    try{
      let data=await api('/api/profiles/'+i+'/history?limit='+(exportFile?1000:100));let events=data.events;
      if(exportFile){while(events.length<data.total){const next=await api('/api/profiles/'+i+'/history?limit=1000&offset='+events.length);if(!next.events.length)break;events.push(...next.events);}const blob=new Blob([JSON.stringify({profile:i,source:'IBKR',exported_at:new Date().toISOString(),events},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='historial-perfil-'+i+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
      const html=events.length?events.map(e=>`<div class="br-event"><strong>${esc(e.label)}</strong> · ${esc(e.ticker)} · ${esc(e.exchange)} · ${esc(e.currency)}<small>${esc(e.level)}: ${number(e.level_price)} · ${esc(e.direction)} · CLOSE · Cierre: ${number(e.close)} · VOLUME · Volumen: ${number(e.volume)}</small><small>Hora de la bolsa: ${clock(e.time,e.timezone,true)} · Hora Perú: ${clock(e.time,'America/Lima',true)}</small>${e.reason?'<small>'+esc(e.reason)+'</small>':''}${e.historical_reconstruction?'<small>Reconstrucción histórica; no es una entrada actual.</small>':''}</div>`).join('')+`<p>${events.length} de ${data.total} eventos. Exportar incluye el historial completo.</p>`:'<p>Todavía no hay eventos registrados.</p>';
      historyCache.set(i,html);el('brHistory'+i).innerHTML=html;
    }catch(e){el('brHistory'+i).textContent=e.message;}
  }
  el('brProfiles').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const i=Number(b.dataset.id);({configure,refresh:()=>refresh(i,true),history:()=>history(i),export:()=>history(i,true)})[b.dataset.action](i);});
  el('brProfiles').addEventListener('change',e=>{if(e.target.dataset.frame){const i=Number(e.target.dataset.frame);frames.set(i,Number(e.target.value));render(i);}if(e.target.dataset.indicators){const i=Number(e.target.dataset.indicators);indicators.set(i,e.target.checked);render(i);}});
  el('brRefreshAll').onclick=()=>refreshAll(true);el('brConnectButton').onclick=connectDialog;
  setInterval(()=>{if(connected)refreshAll();document.querySelectorAll('[data-clock]').forEach(node=>{const p=profiles.get(Number(node.dataset.clock));node.innerHTML='Hora de la bolsa: '+clock(new Date(),p.meta?.timezone)+'<br>Hora Perú: '+clock(new Date(),'America/Lima');});},15000);
  render();window.BreakRetest={refreshAll};
})();
